<?php

/**
 * @file
 * Hook implementations and related functions.
 */

/**
 * Implements hook_menu().
 */
function commerce_pos_currency_denomination_menu() {
  $items = array();

  $items['admin/commerce/config/pos/denomination'] = array(
    'title' => 'Configure Currency Denominations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_currency_denomination_settings_form'),
    'access callback' => '_commerce_pos_access_check',
    'access arguments' => array('process commerce pos sales'),
    'file' => 'includes/commerce_pos_currency_denomination.admin.inc',
  );

  $items['admin/commerce/config/pos/denomination/add'] = array(
    'title' => 'Add Currency Denomination Type',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_currency_add_denomination_type_form'),
    'access callback' => '_commerce_pos_access_check',
    'access arguments' => array('process commerce pos sales'),
    'file' => 'includes/commerce_pos_currency_denomination.admin.inc',
  );

  $items['admin/commerce/config/pos/denomination-type/%/delete'] = array(
    'title' => 'Delete Currency Denomination Type',
    'page callback' => 'drupal_get_form',
    'type' => MENU_CALLBACK,
    'page arguments' => array('commerce_pos_currency_delete_denomination_type_form', 5),
    'access callback' => '_commerce_pos_access_check',
    'access arguments' => array('process commerce pos sales'),
    'file' => 'includes/commerce_pos_currency_denomination.admin.inc',
  );


  return $items;
}

/**
 * Returns all the denominations from the db for a currency code.
 *
 * @param array $currency_codes
 * @return array
 */
function commerce_pos_currency_denomination_get_denominations($currency_codes = array()) {
  $denominations = array();

  // Let's first grab all the denominations under the given currency codes.
  $query = db_select('commerce_pos_currency_denomination', 'd');
  $query->fields('d');

  if ($currency_codes) {
    $currency_ids = commerce_pos_denomination_get_currency_id($currency_codes);
    $query = $query->condition('currency_id', array_keys($currency_ids), 'IN');
  }
  $results = $query->execute();

  // Let's organize them by currency id and then, by denomination id.
  foreach ($results as $result) {
    $denominations[$result->currency_id][$result->denomination_id] = $result;
  }

  return $denominations;
}

/**
 * Returns the configured currency denomination types.
 *
 * @param array $currency_codes
 * @return array
 */
function commerce_pos_denomination_get_currency_types($currency_codes = array()) {
  $query = db_select('commerce_pos_currency_denomination_type', 't');
  $query = $query->fields('t');

  if ($currency_codes) {
    $query = $query->condition('currency_code', $currency_codes, 'IN');
  }

  $denomination_types = $query->execute();

  return $denomination_types;
}

/**
 * Returns the currency ID given currency codes.
 *
 * @param array $currency_codes
 * @return array
 */
function commerce_pos_denomination_get_currency_id($currency_codes) {
  $currency_ids = db_select('commerce_pos_currency_denomination_type', 't')
    ->fields('t', array('currency_id'))
    ->condition('currency_code', $currency_codes, 'IN')
    ->execute()
    ->fetchAllKeyed(0, 1);

  return $currency_ids;
}
